### ISSUE TITLE
mod issue

### ISSUE THREAD

**Issue by ChosenMark** [JongWasTaken/Baubley-Heart-Canisters-Fabric#3] opened 2024-06-26 06:06 UTC
Mod 'Baubley Heart Canisters' (bhc) 1.0.2 requires version 3.7.2 of mod 'Accessories Trinkets Compat Layer' (tclayer), but only the wrong versions are present: 3.8.1-alpha.11/3.8.0!

**Comment by ChosenMark** [comment] 2024-06-26 06:06
please make work with latest version of Accessories Trinkets Compat Layer' (tclayer)

**Comment by JongWasTaken** [comment] 2024-06-26 10:46
Should be fixed in 1.0.4, which I just uploaded to [Modrinth](https://modrinth.com/mod/bhc-fabric/version/uI35czA6) and CurseForge(still pending verification).  
Please tell me if the issue is resolved!

**Comment by ChosenMark** [comment] 2024-06-26 15:36
please dont there mod is very broken still please revert

**Comment by ChosenMark** [comment] 2024-06-26 15:43
> Should be fixed in 1.0.4, which I just uploaded to [Modrinth](https://modrinth.com/mod/bhc-fabric/version/uI35czA6) and CurseForge(still pending verification). Please tell me if the issue is resolved!

dont do it there mod is very broken please remove the need for that mod

**Comment by JongWasTaken** [comment] 2024-06-26 17:12
There is no need to revert, I just relaxed the required trinkets version, which shouldn't cause any issues whatsoever.

**Comment by JongWasTaken** [comment] 2024-06-26 17:14
Also trinkets is recommended anyways so whatever.

**Closed as completed by JongWasTaken** 2024-06-26 17:14 UTC
